In [6]:
import numpy as np
import pandas as pd

In [45]:
# Question 1
# What's the version of NumPy that you installed?

pd.__version__

'2.0.3'

In [56]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

In [46]:
# Question 2
# How many columns are in the dataset?

data.shape[1]

10

In [50]:
# Question 3
# Which columns in the dataset have missing values?

data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [51]:
# Question 4
# How many unique values does the ocean_proximity column have?

data.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [52]:
# Question 5
# What's the average value of the median_house_value for the houses located near the bay?

data[data['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean().round()

259212.0

In [57]:
# Question 6
# Calculate the average of total_bedrooms column in the dataset.

data['total_bedrooms'].mean()

537.8705525375618

In [58]:
# Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

data.fillna(data['total_bedrooms'].mean().round(), inplace=True) 

In [55]:
# Confirm that total_bedrooms has no missing values now

data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [59]:
# Now, calculate the average of total_bedrooms again.

data['total_bedrooms'].mean()

537.8718507751938

In [33]:
# Has it changed?
# Yes - rounded value is 538 in both cases; but values up to 3 digits are 537.870 and 537.871 

In [60]:
# Question 7
# Select all the options located on islands

data_islands = data[data['ocean_proximity'] == 'ISLAND'] 

In [36]:
# Select only columns housing_median_age, total_rooms, total_bedrooms

data_islands_filtered = data_islands[['housing_median_age', 'total_rooms', 'total_bedrooms']] 

In [61]:
# Get the underlying NumPy array. Let's call it X

X = np.array(data_islands_filtered)

In [62]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. 
# Let's call the result XTX

XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [63]:
# Compute the inverse of XTX

inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [40]:
# Create an array y with values [950, 1300, 800, 1000, 1300]

y = [950, 1300, 800, 1000, 1300]

In [64]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

invXTX_XT = np.dot(inverse_XTX, X.T)

In [65]:
w = np.dot(invXTX_XT, y)

In [66]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [67]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w[-1]

5.699229455065586