In [6]:
import numpy as np
import pandas as pd

In [7]:
# Question 1

pd.__version__

'2.0.3'

In [12]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

In [13]:
# Question 2

data.shape[1]

10

In [17]:
# Question 3

data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [18]:
# Question 4

data.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [24]:
# Question 5

data[data['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean().round()

259212.0

In [25]:
# Question 6

data['total_bedrooms'].mean().round()

538.0

In [26]:
data.fillna(data['total_bedrooms'].mean().round(), inplace=True) 

In [27]:
data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [28]:
data['total_bedrooms'].mean().round()

538.0

In [33]:
# Has it changed?
# No

In [35]:
# Question 7

data_islands = data[data['ocean_proximity'] == 'ISLAND'] 

In [36]:
data_islands_filtered = data_islands[['housing_median_age', 'total_rooms', 'total_bedrooms']] 

In [37]:
X = np.array(data_islands_filtered)

In [38]:
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [39]:
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [40]:
y = [950, 1300, 800, 1000, 1300]

In [41]:
invXTX_XT = np.dot(inverse_XTX, X.T)

In [42]:
w = np.dot(invXTX_XT, y)

In [43]:
w

array([23.12330961, -1.48124183,  5.69922946])